name: İstek
description: "İstek form doldurunuz."
labels: [request-tr]
title: "Sorun hakkında kısa açıklama"
body:
  - type: markdown
    attributes:
      value: |
        Merhaba, Sorununu çözmemiz için doldurman gereken bilgiler mevcut. Lütfen mümkün olduğunca açık ve net sorununuzu anlatınız.
  - type: textarea
    attributes:
      label: Yaşadığınız sorundan bahsediniz
      value: |
        apache2 başlatamıyorum başlatmak istediğimde servis hatası almaktayım  
    validations:
      required: true
  - type: textarea
    attributes:
      label: Bu sorunu ne yaptığınızda alıyorsunuz?
      value: |
        sudo systemctl start httpd yaptığımda hata alıyorum.
    validations:
      required: true
  - type: input
    attributes:
      label: Kullandığınız İşletim Sistemi Nedir?
      placeholder: Fedora 37
    validations:
      required: true
  - type: input
    attributes:
      label: Kullandığınız Linux Kernel sürümü?(uname -a)
      description: uname -a komutunu kullanarak deniyebilirsin
      placeholder: "Linux tuxifer 6.1.0-gentoo-x86_64 #1 SMP Mon Dec 12 14:15:02 +03 2022 x86_64 AMD Ryzen 7 5800H with Radeon Graphics AuthenticAMD GNU/Linux"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Log Çıktısı
      value: |
       " "
    validations:
      required: false
  - type: textarea
    attributes:
      label: Çözümünü Biliyor musunuz?
      value: |
        sorunu sudo systemctl enable --now apache2.service yaparak çözdüm.
    validations:
      required: false